apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easytrade

resources:
- accountservice.yaml
- aggregator-service.yaml
- broker-service.yaml
- calculationservice.yaml
- connection-strings.yaml
- contentcreator.yaml
- credit-card-order-service.yaml
- db.yaml
- engine.yaml
- feature-flag-service-setup.yaml
- feature-flag-service.yaml
- frontend.yaml
- frontendreverseproxy.yaml
- loadgen.yaml
- loginservice.yaml
- manager.yaml
- offerservice.yaml
- pricing-service.yaml
- problem-operator.yaml
- rabbitmq.yaml
- third-party-service.yaml

images:
  - name: accountservice
    newName: dynatrace/easytrade-accountservice
    newTag: latest
  - name: aggregator-service
    newName: dynatrace/easytrade-aggregator-service
    newTag: latest
  - name: broker-service
    newName: dynatrace/easytrade-broker-service
    newTag: latest
  - name: calculationservice
    newName: dynatrace/easytrade-calculationservice
    newTag: latest
  - name: contentcreator
    newName: dynatrace/easytrade-contentcreator
    newTag: latest
  - name: credit-card-order-service
    newName: dynatrace/easytrade-credit-card-order-service
    newTag: latest
  - name: db
    newName: dynatrace/easytrade-db
    newTag: latest
  - name: engine
    newName: dynatrace/easytrade-engine
    newTag: latest
  - name: feature-flag-service
    newName: dynatrace/easytrade-feature-flag-service
    newTag: latest
  - name: frontend
    newName: dynatrace/easytrade-frontend
    newTag: latest
  - name: frontendreverseproxy
    newName: dynatrace/easytrade-frontendreverseproxy
    newTag: latest
  - name: loadgen
    newName: dynatrace/easytrade-loadgen
    newTag: latest
  - name: loginservice
    newName: dynatrace/easytrade-loginservice
    newTag: latest
  - name: manager
    newName: dynatrace/easytrade-manager
    newTag: latest
  - name: offerservice
    newName: dynatrace/easytrade-offerservice
    newTag: latest
  - name: pricing-service
    newName: dynatrace/easytrade-pricing-service
    newTag: latest
  - name: problem-operator
    newName: dynatrace/easytrade-problem-operator
    newTag: latest
  - name: rabbitmq
    newName: dynatrace/easytrade-rabbitmq
    newTag: latest
  - name: third-party-service
    newName: dynatrace/easytrade-third-party-service
    newTag: latest
