apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytrade-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easytrade
  template:
    metadata:
      labels:
        app: easytrade
    spec:
      containers:
      - name: easytrade
        image: ghcr.io/joelnorrmarker/easytrade:main
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: easytrade-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: easytrade
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
